pr:
  autoCancel: true

jobs:
- job: 'flake'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      flake8 --ignore=E501,E722,E402 --exclude docs/conf.py .
    displayName: flake8

- job: 'CI_tests'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      ./.ci_stuff/test_dag.sh
    displayName: "CI test"

- job: 'docs'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      cd docs
      make html
    displayName: "make docs"

- job: 'envs'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: 3.7
  - bash: |
      source activate foo
      python .azure-pipelines/testCreateEnv.py -d 1
    displayName: "createEnvs1"
  - bash: |
      source activate foo
      python .azure-pipelines/testCreateEnv.py -d 2
    displayName: "createEnvs2"
  - bash: |
      source activate foo
      python .azure-pipelines/testCreateEnv.py -d 3
    displayName: "createEnvs3"


- job: 'envs_OSX'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation
  - bash: |
      if [ -f /Users/vsts/.conda/pkgs/urls.txt ]; then
        echo "chown"
        sudo chown 501:20 /Users/vsts/.conda/pkgs/urls.txt
      fi
    displayName: Fix OSX permissions
  - template: .azure-pipelines/setup.yml
<<<<<<< HEAD
=======
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.7'
    inputs:
      versionSpec: 3.7
  - bash: |
      source activate foo
      sudo -E python .azure-pipelines/testCreateEnv.py -d 1
    displayName: "createEnvs1"
  - bash: |
      source activate foo
      sudo -E python .azure-pipelines/testCreateEnv.py -d 2
    displayName: "createEnvs2"
>>>>>>> c5f47d93ecc3cc120aff55a10e4a6ab441a5b9d8
  - bash: |
      source activate foo
      sudo -E python .azure-pipelines/testCreateEnv.py -d 3
    displayName: "createEnvs3"
