name: snakepipes_shared_environment_1.0
channels:
 - bioconda
 - conda-forge
dependencies:
 - deeptools=3.0.2
 - seqtk=1.2
 - pigz=2.3.4
 - samtools=1.7
 - fastqc=0.11.7
 - cutadapt=1.16
 - trim-galore=0.4.5
