CSAW:
  memory: 10G
FASTQdownsample:
  memory: 3G
Genrich_peaks:
  memory: 20G
MACS2:
  memory: 8G
__default__:
  memory: 1G
bamCoverage:
  memory: 5G
bamCoverage_RPKM:
  memory: 5G
bamCoverage_coverage:
  memory: 5G
bamCoverage_raw:
  memory: 5G
bamCoverage_unique_mappings:
  memory: 5G
create_snpgenome:
  memory: 30G
filter_reads_umi:
  memory: 10G
histoneHMM:
  memory: 4G
plotCorrelation_pearson:
  memory: 3G
plotCorrelation_pearson_allelic:
  memory: 5G
plotCorrelation_spearman:
  memory: 3G
plotCorrelation_spearman_allelic:
  memory: 2G
plotCoverage:
  memory: 1G
plotEnrichment:
  memory: 1G
plotFingerprint:
  memory: 1G
plotPCA:
  memory: 4G
plotPCA_allelic:
  memory: 4G
plot_heatmap_CSAW_up:
  memory: 10G
snakePipes_cluster_logDir: cluster_logs
snakemake_cluster_cmd: module load slurm; SlurmEasy --mem-per-cpu {cluster.memory}
  --threads {threads} --log cluster_logs --name {rule}.snakemake
snakemake_latency_wait: 300
snp_split:
  memory: 10G
